version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shortener
    ports: ["5432:5432"]
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis:6
    ports: ["6379:6379"]
volumes:
  db-data:
